apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: creez-backend
  name: creez-backend
  namespace: int-creez
spec:
  replicas: 1
  selector:
    matchLabels:
      app: creez-backend
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 10%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: creez-backend
    spec:
      containers:
        - command:
            - python
            - main.py
          image: lighton-cn-beijing.cr.volces.com/lighton/creez-backend:20260213
          imagePullPolicy: Always
          name: creez-backend
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: "500m"
              memory: 1Gi
          envFrom:
            - secretRef:
                name: creez-backend-secret
          volumeMounts:
            - mountPath: /root/config/
              name: app-config
      volumes:
        - configMap:
            name: creez-backend
          name: app-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler

---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: creez-backend
    prometheus_monitoring: enabled
  name: creez-backend
  namespace: int-creez
spec:
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: creez-backend
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: creez-backend
  namespace: int-creez
  labels:
    app: creez-backend
    role: int
data:
  ConfigRole: Int
